---
# handlers file for apache

- name: Reload firewalld
  service:
    name: firewalld
    state: reloaded
  when: ansible_os_family == 'RedHat'

- name: Restart apache
  service:
    name: httpd
    state: restarted
  when: ansible_os_family == 'RedHat'

- name: Reload ufw
  service:
    name: ufw
    state: reloaded
  when: ansible_os_family == 'Debian'

- name: Restart apache
  service:
    name: apache2
    state: restarted
  when: ansible_os_family == 'Debian'

