---
# tasks file for apache

  - name: Instalar apache
    dnf:
      name: httpd
      state: present
    when: ansible_os_family == 'RedHat'

  - name: Abrir puertos del firewall
    firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: true
      immediate: true
    loop:
    - http
    - https
    when: ansible_os_family == 'RedHat'

  - name: Iniciar y habilitar httpd service
    service:
      name: httpd
      enabled: true
      state: started
    when: ansible_os_family == 'RedHat'

