---
- name: Instalar y configurar Tomcat en Podman 
  hosts: redhat
  become: yes
  remote_user: ansible

  roles:
    - role: podman

  tasks:

    - name: Crear directorio para el contenedor
      file:
        path: /ansible/contenedor/appweb
        state: directory

    - name: Copiar todo.war a la ruta
      copy:
        src: ./files/todo.war
        dest: /ansible/contenedor/appweb/todo.war

    - name: Copiar app.properties a la ruta
      copy:
        src: ./files/app.properties
        dest: /ansible/contenedor/appweb/app.properties
        
    - name: Copiar dockerfile a la ruta
      copy:
        src: ./files/Dockerfile
        dest: /ansible/contenedor/appweb/Dockerfile

    - name: Configurar y ejecutar
      containers.podman.podman_image:
        name: "appweb"
        path: '/ansible/contenedor/appweb/'
        build:
          format: docker
        state: present
      register: results

    - name: Iniciar contenedor
      containers.podman.podman_container:
        name: appweb
        image: appweb
        state: started
        etc_hosts:
          other: "192.168.56.103"
        ports:
          - "8080:8080"  


