---
- name: Instalar y configurar Tomcat en Podman 
  hosts: redhat
  become: yes

  roles:
    - role: podman

  tasks:

    - name: Crear directorio para el contenedor
      file:
        path: /ansible/contenedor/appweb
        state: directory

    - name: Copiar todo.war a la ruta
      copy:
        src: ./files/todo.war
        dest: /ansible/contenedor/appweb/todo.war

    - name: Copiar app.properties a la ruta
      copy:
        src: ./files/app.properties
        dest: /ansible/contenedor/appweb/app.properties
        


    - name: Crear imagen y configurar el contenedor con Podman
      podman_image:
        name: appweb
        build:
          context: /ansible/contenedor/appweb/
          dockerfile:
            FROM tomcat:9.0
            RUN mkdir /opt/config
            COPY app.properties /opt/config
            COPY todo.war /usr/local/tomcat/webapps/
            EXPOSE 8080
            CMD ["catalina.sh", "run"]
        state: present


    - name: Configurar y ejecutar
      containers.podman.podman_image:
        name: "appweb"
        path: '/opt/config'
        build:
         format: docker
        state: present
      register: results

        # - name: Crear imagen 
        # command: podman build -t appweb /ansible/contenedor/appweb/
        #args:
        #executable: /bin/bash

