---
- name: Instalar y configurar Tomcat en Podman 
  hosts: Redhat
  become: yes

  roles:
    - role: podman

  tasks:

    - name: Crear directorio para el contenedor
      file:
        path: /ansible/contenedor/appweb
        state: directory

    - name: Copiar todo.war a la ruta
      copy:
        src: /files/todo.war
        dest: /ansible/contenedor/appweb/todo.war
        remote_src: yes

    - name: Copiar app.properties a la ruta
      copy:
        src: /files/app.properties
        dest: /ansible/contenedor/appweb/app.properties
        remote_src: yes


    - name: Crear imagen y configurar el contenedor con Podman
      podman_image:
        name: appweb
        build:
          context: /ansible/contenedor/appweb/
          dockerfile:
            FROM tomcat:9.0
            RUN mkdir /opt/config
            COPY app.properties /opt/config
            COPY todo.war /usr/local/tomcat/webapps/
            EXPOSE 8080
            CMD ["catalina.sh", "run"]
        state: present


    - name: Configurar y ejecutar
      podman_container:
        name: appweb
        image: appweb
        state: started
        interactive: no
        tty: yes
        ports:
         - "8080:8080"
        volumes:
         - "/ansible/contenedor/appweb:/ruta/al/montaje:Z"


        # - name: Crear imagen 
        # command: podman build -t appweb /ansible/contenedor/appweb/
        #args:
        #executable: /bin/bash

