---
- hosts: debian
  remote_user: ansible
  become: yes
  vars_files:
    - pass.yml
    - todopass.yml
    
  roles:
    - role: mariadb
    - role: firewall.debian  

  tasks:

  - name: Crear usuario todo en mariadb
    mysql_user:
      login_user: root
      login_password: "{{ pass }}"
      name: todo
      host: "{{ item }}"
      priv: '*.*:ALL,GRANT'
      password: "{{ todopass }}"
    loop:
      - 127.0.0.1
      - localhost
      - 192.168.56.%

  - name: Crear base de datos todo en mariadb
    mysql_db:
      login_user: root
      login_password: "{{ pass }}"
      name: todo

  - name: Crear directorio para repositorio sql
    file:
      path: /ansible/sql
      state: directory


  - name: Copiar statament de la bd todo a la ruta
    copy:
      src: ./files/statement_todo.sql
      dest: /ansible/sql/statement_todo.sql
        

  - name: Crear estructura bd todo
    mysql_db:
     login_user: root
     login_password: "{{ pass }}"
     name: todo
     state: present
     target: /ansible/sql/statement_todo.sql

  
      

