---
# tasks file for firewall.debian

- name:  Configuracion Firewall incoming allow  en Debian
  ufw:
    rule: allow 
    direction: in 
    state: enabled
  when: ansible_os_family == 'Debian'

- name:  Configuracion Firewall outcoming deny  en Debian
  ufw:
    rule: deny
    direction: out
    state: enabled
  when: ansible_os_family == 'Debian'



  #- name: Habilitar UFW en Debian
  #ufw:
          # state: enabled
- name: ufw service enable and start
  service:
    name: ufw
    state: started
    enabled: yes
  when: ansible_os_family == 'Debian'
  
