---
# tasks file for podman
#RedHat

- name: Instalar Podman en RedHat
  dnf:
   name: podman
   state: present
  when: ansible_os_family == 'RedHat'

- name: Habilitar podman para que inicie con el sistema en RedHat
  service:
   name: podman
   enabled: true
   state: started
  when: ansible_os_family == 'RedHat'

#Debian

- name: Instalar Podman en Debian
  apt:
   name: podman
   state: present
  when: ansible_os_family == 'Debian'

- name: Habilitar podman para que inicie con el sistema en Debian
  service:
   name: podman
   enabled: true
   state: started
  when: ansible_os_family == 'Debian'
 
