---
# tasks file for apache

  - name: Instalar mariadb en RedHat
    dnf:
      name: mariadb-server
      state: present
    when: ansible_os_family == 'RedHat'

  - name: Iniciar y habilitar en RedHat
    service:
      name: mariadb
      enabled: true
      state: started
    when: ansible_os_family == 'RedHat'

  - name: Abrir el puerto 3306 en el firewall en RedHat
    firewalld:
      port: 3306/tcp
      permanent: yes
      state: enabled
    when: ansible_os_family == 'RedHat'
    notify: Reload firewalld


  - name: Instalar mariadb en Debian
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - mariadb-server
      - mariadb-client
      - python3-pip
    when: ansible_os_family == 'Debian'


  - name: Instalar PyMySQL en Debian
    pip:
      name: PyMySQL
      executable: pip3
      extra_args: --user
    when: ansible_os_family == 'Debian'

    
  - name: Iniciar y habilitar el servicio mariadb en Debian
    service:
      name: mariadb
      state: started
      enabled: yes
    when: ansible_os_family == 'Debian'
    

  - name: Abrir el puerto en el firewall en Debian
    ufw:
      rule: allow
      port: '3306'
      proto: tcp
      # notify: Reload ufw
    when: ansible_os_family == 'Debian'
    
  
  - name: Configure mariadb to listen on all interfaces
    lineinfile:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: '^bind-address'
      line: bind-address = 0.0.0.0
    notify: Restart mariadb server


  - name: Update MariaDB root password
    mysql_user:
      login_unix_socket: /var/run/mysqld/mysqld.sock
      login_user: root
      login_password: "{{ pass }}"
      check_implicit_admin: yes 
      name: root
      host: "{{ item }}"
      password: "{{ pass }}" 
    loop:
      - 127.0.0.1
      - localhost
      - 192.168.56.%


  - name: Delete anonymous user
    mysql_user:
      login_host: localhost
      login_user: root
      login_password: "{{ pass }}"
      name: ""
      host_all: yes
      state: absent
  

  - name: Delete test database
    mysql_db:
      login_host: localhost
      login_user: root
      login_password: "{{ pass }}"
      name: test
      state: absent


