---
# tasks file for apache

  - name: Instalar mariadb en RedHat
    dnf:
      name: mariadb-server
      state: present
    when: ansible_os_family == 'RedHat'

  - name: Iniciar y habilitar en RedHat
    service:
      name: mariadb
      enabled: true
      state: started
    when: ansible_os_family == 'RedHat'

    - name: Abrir el puerto 3306 en el firewall en RedHat
      firewalld:
        port: 3306/tcp
        permanent: yes
        state: enabled
      when: ansible_os_family == 'RedHat'
      notify: Reload firewalld



 - name: Mariadb server install
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - mariadb-server
      - mariadb-client
      - python3-pip
    when: ansible_os_family == 'Debian'


  - name: Install PyMySQL with pip
    pip:
      name: PyMySQL
      executable: pip3
      extra_args: --user
    when: ansible_os_family == 'Debian'

    
  - name: Mariadb service enable and start
    service:
      name: mariadb
      state: started
      enabled: yes
    when: ansible_os_family == 'Debian'
    

- name: Abrir el puerto 3306 en el firewall en Debian
    ufw:
      rule: allow
      port: 3306
      proto: tcp
      notify: Reload ufw
    when: ansible_os_family == 'Debian'
  


