---
# tasks file for web_apache

- name: Instalar y configurar Servidor Apache
  hosts: Redhat
  become: yes
  remote_user: sysadmin

  tasks:

  - name: Instalar apache
    dnf:
      name: httpd
      state: present

  - name: Abrir puertos del firewall
    firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: true
      immediate: true
    loop:
    - http
    - https

  - name: Iniciar y habilitar httpd service
    service:
      name: httpd
      enabled: true
      state: started

